import type { Metadata } from 'next';

import { avenirNext } from '@/assets/fonts';
import { cn } from '@/utils/cn';

import { Header } from './_components/Header';
import { Providers } from './providers';

import '@/assets/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ru'>
      <body className={cn(avenirNext.className, 'bg-[#E7F1FF]')}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
