import type { Metadata } from 'next';

import { avenirNext } from '@/assets/fonts';

import { Header } from './(components)/Header';

import '@/assets/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ru'>
      <body className={avenirNext.className}>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
