import type { Metadata } from 'next';

import { avenirNext } from '@/assets/fonts';

import { Header } from './_components/Header';
import { Providers } from './providers';

import '@/assets/styles/globals.css';

export const metadata: Metadata = {
  title: 'Карта Путешествия Студента СурГУ',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ru'>
      <body className={avenirNext.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
